# Generated by Django 4.2.3 on 2023-12-07 09:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategotiasAdmin',
            fields=[
                ('categoria_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='noticias.categoria')),
            ],
            bases=('noticias.categoria',),
        ),
        migrations.CreateModel(
            name='ComentariosAdmin',
            fields=[
                ('comentario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='noticias.comentario')),
            ],
            bases=('noticias.comentario',),
        ),
        migrations.CreateModel(
            name='NoticiasAdmin',
            fields=[
                ('noticia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='noticias.noticia')),
            ],
            bases=('noticias.noticia',),
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ('-publicado',)},
        ),
        migrations.AddField(
            model_name='noticia',
            name='publicado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(default='static/noimagen.png', upload_to='noticias'),
        ),
    ]
