# Generated by Django 4.2.3 on 2023-12-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_categotiasadmin_comentariosadmin_noticiasadmin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ('-creado',)},
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='fecha',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='publicado',
            new_name='modificado',
        ),
        migrations.AddField(
            model_name='noticia',
            name='resumen',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
